[project]
name = "rl-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.4.1",
    "pydantic>=2.12.5",
    "rich>=14.2.0",
    "textual>=0.88.1",
    "torch>=2.9.1",
]
